[project]
name = "komarucardsbot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "toml>=0.10.2",
    "telethon==1.42.0",
]
